version: "3.8"
services:
  test:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile
    env_file: .env.test
  prod:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile
    env_file: .env.prod

