# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy Discord Bot to App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: docker build . -t dopebot
        
      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/803405501117/locations/global/workloadIdentityPools/automation-pool/providers/automation-provider'
          service_account: 'automation@dopewars-live.iam.gserviceaccount.com'
          
        # DEBUG: See if this is actually working
      - name: DEBUG Auth
        run: |-
          gcloud iam service-accounts list
